name: DevOps - Postman Newman test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  newman:
    name: Postman Newman FakeAPI test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Runing newman
      uses: matt-ball/newman-action@master
      with:
        collection: ecommerce-api-collection.json
        environment: ecommerce-environment.json    
       